name: Tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  phpunit:
    runs-on: ubuntu-latest
     
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
 
    - name: Install composer dependencies
      run: |
        composer install --no-scripts
        composer update
 
    - name: Prepare Laravel Application
      run: |
        cp .env.ci .env
        php artisan key:generate
 
    - name: Setup Javascript
      run: |
        npm ci
        npm run build
 
    - name: Run tests
      run: php artisan test
