name: Tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  phpunit:
    runs-on: ubuntu-latest
     
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
  
    - name: Install composer dependencies
      run: |
        ./vendor/bin/sail composer install --no-scripts
        ./vendor/bin/sail update
 
    - name: Prepare Laravel Application
      run: |
        cp .env.ci .env
        ./vendor/bin/sail artisan key:generate
 
    - name: Setup Javascript
      run: |
        ./vendor/bin/sail npm ci
        ./vendor/bin/sail npm run build
 
    - name: Run tests
      run: |
        ./vendor/bin/sail test
