on: 
  push:
    branches: [ main ]

name: Tests
jobs:
  laravel-tests:
    runs-on: ubuntu-latest
 
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: testing
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        coverage: xdebug

    - uses: actions/checkout@v3

    - name: Copy .env
      run: cp .env.ci .env
    
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Generate key
      run: php artisan key:generate

    - name: Run PHPUnit tests
      run: vendor/bin/phpunit
    
    - name: phpunit-coverage-badge
      uses: timkrase/phpunit-coverage-badge@v1.2.0